@startuml
start
   while (Reporter has issue?) is (yes)
    :**TODO:** Create a new browser profile;
    if (Is issue **not reproducible** in a new profile?) then (yes)
    :Refresh old profile
    will reset all about:config 
    settings and remove addons;
    break
  else (no)
    :**TODO:** Share steps to reproduce the issue with others;
    if (Issue reproducable by others?) then (yes)
      :Might be an actual
      firefox issue;
    :Sad End (1) 
    **TODO:** Check bugzilla;
    stop
    else (no)
      :Likely not a firefox issue
      but a different system, device 
      or software issue;
    :Sad End (2) 
    **TODO:** n/a;
    stop
    endif
  endif
  endwhile (no)
  label HappyEnd
  :Happy End
  Continue Browsing;
 stop
@enduml
