name: "Report a Bug 🪲"
description: "Use this if something is not working as you would expect"
title: " < insert addon name > : < insert short title >"
labels: ["🪲 Bug"]
body:
  - type: dropdown
    attributes:
      label: "Can you reproduce the issue in a new firefox profile?"
      options: 
        - "not checked"
        - "no"
        - "yes"
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: "Steps to Reproduce"
      placeholder: |        
        Examples: 
          1. open the addon preferences page
          2. change option x to z
          3. open a new tab and navigate to url https://example.net ...
          4. ... 
        
  - type: textarea
    attributes:
      label: "Expected Result"
      placeholder: |
        Examples: 
        - Windows should open that shows X
        - Data should be inside the clipboard / saved

  - type: textarea
    attributes:
      label: "Actual Result"
      placeholder: |
        Examples: 
        - Nothing happend (no reaction)
        - Error/Blank page was shown
