name: Report a Bug 🪲
description: If something isn't working as you'd expect, please use this template to report 
title: "[addon name]: <short title>"
labels: ["🪲 Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time submit this issue!
  
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. open a temporary browser profile  
        2. open page ...
        3. click on ...
        
  - type: textarea
    id: expected-result
    attributes:
      label: Expected Result
      placeholder: |
        Examples: 
        - Windows should open that shows X
        - Data should be inside the clipboard / saved

  - type: textarea
    id: actual-result
    attributes:
      label: Actual Result
      placeholder: |
        Examples: 
        - Nothing happend (no reaction)
        - Error/blank page was show
        - Data was not saved

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information 
      placeholder: |
        Examples: 
        1. screen-shots/captures
        2. browser (+version)
        3. addon (+version)
