name: "🪲 Report a Bug"
description: "Use this if something does not work as you would expect"
title: "Which addon is this bug about? And what is the gist of the bug?"
assignees:  ["igorlogius"]
labels: ["🪲 Bug"]
body:

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Reproduction steps"
      placeholder: |
        List the necessary steps for reproduction
        
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Expected result"
      placeholder: |
        Describe what you expected to happen

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Actual result"
      placeholder: |
        Describe what actually happend
