name: "🪲 Report a Bug"
description: "Use this if something doesn't work"
title: "[repo name] brief title"
assignees:  ["igorlogius"]
labels: ["🪲 Bug"]
body:

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Description"
      placeholder: |
        1. Reproduction Steps
        2. Expected Result
        3. Actual Result
