name: "🪲 Report a Bug"
description: "Use this if something does not work as expected"
title: "[addon name] your brief title"
assignees:  ["igorlogius"]
labels: ["🪲 Bug"]
body:

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Reproduction steps"
      placeholder: |
        List the necessary steps for reproduction
        
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Expected result"
      placeholder: |
        Describe what you expected to happen

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Actual result"
      placeholder: |
        Describe what actually happend
