name: Something else?
description: Anything else goes here
title: "<short title>"
labels: ["🛟 Question"]
body:
  - type: markdown
    attributes:
      value: |
        What's on your mind? 
        
  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: |
          - Why are your addons so ugly?
