name: "💡 Make a Suggestion"
description: "Use this if for feature and change requests for existing projects"
title: "[repo name] brief title"
assignees:  ["igorlogius"]
labels: ["💡 Suggestion"]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Description"
