name: "Make a Suggestion 💡"
description: "Use this if you want to make a suggestion"
title: "Which addon is this suggestion about? And what is the gist of it?"
labels: ["💡 Suggestion"]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Please describe your suggestion"
      placeholder: |
        - i want X todo Y, because that is simpler and fits better into workflow Z
        - i think A should be like B because C
