name: "Make a Suggestion 💡"
description: "Use this if you want to make a suggestion"
labels: ["💡 Suggestion"]
body:
  - type: input
    attributes:
      label: "Which addon is this suggestion for?"
      placeholder: e.g. Copy Tabs, Link Extras, ...

  - type: textarea
    attributes:
      label: "Please describe your suggestion"
      placeholder: |
        - i want X todo Y, because that is simpler and fits better into workflow Z
        - i think A should be like B because C
