name: Make a Suggestion 💡
description: Use this if you have an improvement suggestion or want to request a feature
title: "addon name: title"
labels: ["💡 Suggestion"]
body:
  - type: textarea
    id: expected-result
    attributes:
      label: Describe your request or suggestion
      placeholder: |
        - i want X todo Y, because thats simpler/quicker fits into workflow Z
        - i think A should be like B because C
