name: "💡 Make a Suggestion"
description: "Use this if for feature and change requests for existing projects"
title: "repo / title"
labels: ["💡 Suggestion"]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Description"
      value: |
        A. Problem Description (aka. usecase motivation)
        B. Solution suggestion
        
