name: "💡 Make a Suggestion"
description: "Use this if you want to make a suggestion"
title: "[addon name] brief title"
assignees:  ["igorlogius"]
labels: ["💡 Suggestion"]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Describe your suggestion"
