name: "Make a Suggestion 💡"
description: "Use this if you want to make a suggestion"
title: "< addon name >: < your title >"
labels: ["💡 Suggestion"]
body:
  - type: textarea
    attributes:
      label: "Please describe your suggestion"
      placeholder: |
        - i want X todo Y, because that is simpler and fits better into workflow Z
        - i think A should be like B because C
