name: Bug Report Form
description: File a bug report.
title: "[Project]: <title>"
labels: ["bug", "triage"]
assignees:
  - igorlogius
body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the necessary steps to reproduce the issue
      placeholder: |
        1. Create a temporary new profile 
        2. install addon 
        3. open page
        4. ... 

  - type: textarea
    id: expected-result
    attributes:
      label: Expected Result
      description: What did you expect to happen?
      placeholder: |
        Should work

  - type: textarea
    id: actual-result
    attributes:
      label: Expected Result
      description: What did you expect to happen?
      placeholder: |
        Did not work. 
