name: Report a Bug 
description: File a bug report.
title: "[Projectname]: <title>"
labels: ["bug", "triage"]
assignees:
  - igorlogius
body:

  - type: markdown
    attributes:
      value: |
        Thank you for taking the time submit this bug report!
        
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please tell us, what steps are necessary to reproduce the issue?
      placeholder: |
        0. use temporary browser profile  
        1. install addon 
        2. open page ...
        3. scroll to ...
        4. click on ...
        5. 
        

  - type: textarea
    id: expected-result
    attributes:
      label: Expected Result
      description: What did you expect to happen?
      placeholder: |
        Examples: 
        - Windows should open that shows X
        - Data should be inside the clipboard 
        - Data should have been saved
        - ...

  - type: textarea
    id: actual-result
    attributes:
      label: Actual Result
      description: What actually happened?
      placeholder: |
        Examples: 
        - Nothing happend (no reaction)
        - Error/blank page was show
        - Data was not saved
        - ...

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information 
      description: Any else that might be useful to know about?
      placeholder: |
        Examples: 
        1. screen-shots/captures
        2. browser (+version)
        3. addon (+version)
        4. ... 
