name: Something else?
description: Anything else goes here
title: "<short title>"
labels: ["🛟 Question"]
assignees:
  - igorlogius
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time submit this issue!
        
  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: |
          - Why are your addons so ugly?
