name: "🛟 Ask a Question"
description: "Use this for anything that is not a bug report or a suggestion"
title: "[addon name] your brief title"
assignees:  ["igorlogius"]
labels: ["🛟 Support"]
body:
  - type: textarea
    attributes:
      label: "What's on your mind?"
