name: Something else? 
description: Use this for anything that is not a bug report or a suggestion
title: "title"
labels: ["🔍 Mystery"]
body:
  - type: textarea
    attributes:
      label: What is on your mind?
