name: Something else? 
description: Use this for anything that is not a bug report or a suggestion
title: "title"
labels: ["🔍 Mystery"]
body:
  - type: textarea
    id: question
    attributes:
      label: What's on your mind? 
      placeholder: |
          - Enter text here
