name: "🛟 Got a question, need help or something else? "
description: "Use this for anything that is not a bug or a suggestion"
title: "What addon/extension or question is this issue about? And what is the gist of it?"
labels: ["🛟 Support"]
body:
  - type: textarea
    attributes:
      label: "What is on your mind?"
